// <auto-generated />
using System;
using Bibliotheca.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bibliotheca.Core.Migrations
{
    [DbContext(typeof(BibliothecaContext))]
    [Migration("20210302180434_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("Bibliotheca.Core.Tables.AccountTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountTable");
                });

            modelBuilder.Entity("Bibliotheca.Core.Tables.BookTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Status");

                    b.ToTable("BookTable");
                });

            modelBuilder.Entity("Bibliotheca.Core.Tables.BookTable", b =>
                {
                    b.HasOne("Bibliotheca.Core.Tables.AccountTable", "Account")
                        .WithMany("Books")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
